### ISSUE TITLE
AttributeError: type object 'Tensor' has no attribute '_make_wrapper_subclass'

### ISSUE THREAD

**Issue by dzk9528** [microsoft/nni#5538]
**Describe the issue**:
When I add the profiler as tutorial instructed below:
```python
from nni.nas.strategy.middleware import Filter, Chain
from nni.nas.profiler.pytorch.flops import NumParamsProfiler
profiler = NumParamsProfiler(model_space, torch.randn(1, 1, 28, 28))
search_strategy = Chain(
    strategy.Random(),
    Filter(lambda sample: profiler.profile(sample) < args.max_num_params)
)
```
This error appeared:
```bash
  File "/usr/local/lib/python3.8/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 301, in __new__
    r: ShapeTensor = torch.Tensor._make_wrapper_subclass(  # type: ignore
AttributeError: type object 'Tensor' has no attribute '_make_wrapper_subclass'
```

**Environment**:
- NNI version: latest(Build from source and use Dockerfile in master branch)
- Training service (local|remote|pai|aml|etc): local
- Client OS: Unbuntu
- Python version: 3.8
- PyTorch/TensorFlow version: 1.10.2
- Is conda/virtualenv/venv used?: No
- Is running in Docker?: Yes

**Configuration**:
 - Experiment config (remember to remove secrets!): Same as Latest Version in Hello NAS
 - Search space: Random

**Comment by matluster** [comment]
Please upgrade your pytorch to some version between 1.11 and 1.13.

**Comment by dzk9528** [comment]
> ```python
> torch.randn(1, 1, 28, 28)
> ```

Thanks for the reply, when I upgrade to 1.13, it still have the same error.

**Comment by ultmaster** [comment]
Any noticeable warnings?

**Comment by dzk9528** [comment]
@ultmaster Here is the warning:
```bash
WARNING: Shape information is not explicitly propagated when executing aten.max_pool2d_with_indices.default, and and none of its parent modules have a shape inference formula. Shape inference is likely to fail. Module calling stack:
  - '' (type: __main__.MyModelSpace, NO shape formula) 
```

**Comment by matluster** [comment]
Either register a formula for `aten.max_pool2d_with_indices.default` like what was done here:

https://github.com/microsoft/nni/blob/fea29c7cf5fea0bdfe11e908d50bb93337ef5d3f/nni/nas/profiler/pytorch/utils/shape_formula.py#L371

or use `nn.MaxPool2d` as it looks like it's already been registered:

https://github.com/microsoft/nni/blob/fea29c7cf5fea0bdfe11e908d50bb93337ef5d3f/nni/nas/profiler/pytorch/utils/shape_formula.py#L349

**Comment by dzk9528** [comment]
@matluster aAnother error appeared after I change to `nn.MaxPool2d`
```
[2023-05-11 18:30:08] Setting up...                                                                                                                                                                                                                                                 [2/1871]
[2023-05-11 18:30:08] Web portal URLs: http://127.0.0.1:8080 http://172.18.18.103:8080 http://172.17.0.1:8080                                                                                                                                                                               
[2023-05-11 18:30:08] Successfully update searchSpace.                                                                                                                                                                                                                                      
[2023-05-11 18:30:08] Checkpoint saved to /root/nni-experiments/62m5slcr/checkpoint.                                                                                                                                                                                                        
[2023-05-11 18:30:08] Experiment initialized successfully. Starting exploration strategy...                                                                                                                                                                                                 
[2023-05-11 18:30:08] ERROR: Strategy failed to execute.                                                                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                                                          
  File "/home/dzhang/Documents/ml-experimental/TinyNAS/nas_tutorial/random_search.py", line 173, in <module>                                                                                                                                                                                
    exp.run(debug=True)                                                                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.10/dist-packages/nni/experiment/experiment.py", line 235, in run                                                                                                                                                                                             
    return self._run_impl(port, wait_completion, debug)                                                                                                                                                                                                                                     3" 18:00 11-May-23
  File "/usr/local/lib/python3.10/dist-packages/nni/experiment/experiment.py", line 204, in _run_impl
    self.start(port, debug)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/experiment/experiment.py", line 270, in start
    self._start_engine_and_strategy()
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/experiment/experiment.py", line 230, in _start_engine_and_strategy
    self.strategy.run()
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/strategy/middleware.py", line 89, in run
    return self._strategy.run()
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/strategy/base.py", line 170, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/strategy/bruteforce.py", line 223, in _run
    self.engine.submit_models(model)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/strategy/middleware.py", line 292, in submit_models
    if self.filter_fn(model):
  File "/home/dzhang/Documents/ml-experimental/TinyNAS/nas_tutorial/random_search.py", line 163, in <lambda>
    Filter(lambda sample: profiler.profile(sample) < 1000*1000)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/profiler.py", line 44, in profile
    return self.expression.evaluate(sample)
  File "/usr/local/lib/python3.10/dist-packages/nni/mutable/symbol.py", line 175, in evaluate
    eval_args.append(arg.evaluate(values))
  File "/usr/local/lib/python3.10/dist-packages/nni/mutable/symbol.py", line 175, in evaluate
    eval_args.append(arg.evaluate(values))
  File "/usr/local/lib/python3.10/dist-packages/nni/mutable/symbol.py", line 175, in evaluate
    eval_args.append(arg.evaluate(values))
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.10/dist-packages/nni/mutable/symbol.py", line 543, in evaluate
    value = next(values)
TypeError: 'SimplifiedModelSpace' object is not an iterator
```

**Comment by matluster** [comment]
This line here:

```python
Filter(lambda sample: profiler.profile(sample) < 1000*1000)
```

It should be

```python
Filter(lambda model: profiler.profile(model.sample) < 1000*1000)
```

**Comment by dzk9528** [comment]
@matluster The issue is solved. Thanks!
