### ISSUE TITLE
issue concerning PyTorch

### ISSUE THREAD

**Issue by Passero86** [microsoft/nni#2486]
**Short summary about the issue/question**:
I am using the FeatureGradientSelector in nni, it throws an ImportError: cannot import name '_DataLoaderIter' and '_utils'. I wonder which version of PyTorch you are using, because for PyTorch of 1.5.0, it won't work.

**Comment by xuehui1991** [comment]
Hello @Passero86 
You can reference [here](https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/feature_engineering/gradient_selector/requirements.txt).

It works on torch 1.1.0. Thanks.
